package issue48;

/**
 * Simple method that we'll test with TestNG, and view results generated by ReportNG
 */
public class Arithmetic {
    public int sum(int i, int j) {
        return i + j;
    }
}
